//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rectify11ControlCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rectify11ControlCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bloom {
            get {
                object obj = ResourceManager.GetObject("bloom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings
        ///{
        ///	priority=1
        ///	exclude.where = !process.is_explorer
        ///	showdelay = 100
        ///	// Options to allow modification of system items
        ///	modify.remove.duplicate=1
        ///	tip
        ///	{
        ///		enabled=1
        ///		opacity=100
        ///		width=400
        ///		radius=1
        ///		time=1.25
        ///		padding=[10,10]
        ///	}
        ///}
        ///theme
        ///{
        ///	name=&quot;modern&quot;
        ///}
        ///import &apos;imports/theme.nss&apos;
        ///import &apos;imports/images.nss&apos;
        ///
        ///import &apos;imports/modify.nss&apos;
        ///modify(where=this.title.length &gt; 15 menu=title.more_options)
        ///
        ///menu(mode=&quot;multiple&quot; title=&quot;Pin/Unpin&quot; image=icon.pin) {}
        ///menu(mod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config1 {
            get {
                return ResourceManager.GetString("config1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings
        ///{
        ///	priority=1
        ///	exclude.where = !process.is_explorer
        ///	showdelay = 100
        ///	// Options to allow modification of system items
        ///	modify.remove.duplicate=1
        ///	tip
        ///	{
        ///		enabled=1
        ///		opacity=100
        ///		width=400
        ///		radius=1
        ///		time=1.25
        ///		padding=[10,10]
        ///	}
        ///}
        ///theme
        ///{
        ///	name=&quot;modern&quot;
        ///}
        ///import &apos;imports/theme.nss&apos;
        ///import &apos;imports/images.nss&apos;
        ///
        ///import &apos;imports/modify.nss&apos;
        ///
        ///menu(mode=&quot;multiple&quot; title=&quot;Pin/Unpin&quot; image=icon.pin) {}
        ///menu(mode=&quot;multiple&quot; title=title.more_options image=icon.more_options) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config2 {
            get {
                return ResourceManager.GetString("config2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkPreview {
            get {
                object obj = ResourceManager.GetObject("DarkPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap installprogress {
            get {
                object obj = ResourceManager.GetObject("installprogress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightPreview {
            get {
                object obj = ResourceManager.GetObject("LightPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previewIcon {
            get {
                object obj = ResourceManager.GetObject("previewIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PreviewImg {
            get {
                object obj = ResourceManager.GetObject("PreviewImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PreviewPane {
            get {
                object obj = ResourceManager.GetObject("PreviewPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
